/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.AllergiesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.AllergiesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.AllergiesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.AllergiesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.AllergiesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.AllergiesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.AllergiesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.AllergiesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.AllergiesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.AllergiesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.AllergiesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.AllergiesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.AllergiesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.AllergiesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).allergies.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.AllergiesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).allergies.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
