/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.AppointmentInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.AppointmentInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.AppointmentInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.AppointmentInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.AppointmentInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.AppointmentInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.AppointmentInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.AppointmentInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.AppointmentInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.AppointmentInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.AppointmentInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.AppointmentInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.AppointmentInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.AppointmentInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).appointment.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.AppointmentInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).appointment.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
