/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.AssetInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.aggregate(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.AssetInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).asset.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.AssetInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).asset.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.AssetInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.AssetInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.AssetInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.AssetInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.AssetInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.AssetInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).asset.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.AssetInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).asset.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.AssetInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).asset.update(input as any)),
      ),

    count: procedure
      .input($Schema.AssetInputSchema.count.optional())
      .query(({ ctx, input }) => checkRead(db(ctx).asset.count(input as any))),
  } satisfies TRPCRouterRecord);
}
