/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.CidInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).cid.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.CidInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.CidInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.CidInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.CidInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.CidInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).cid.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.CidInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).cid.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.CidInputSchema.findMany.optional())
      .query(({ ctx, input }) => checkRead(db(ctx).cid.findMany(input as any))),

    findUnique: procedure
      .input($Schema.CidInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).cid.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.CidInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).cid.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.CidInputSchema.groupBy)
      .query(({ ctx, input }) => checkRead(db(ctx).cid.groupBy(input as any))),

    updateMany: procedure
      .input($Schema.CidInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.CidInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.CidInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).cid.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.CidInputSchema.count.optional())
      .query(({ ctx, input }) => checkRead(db(ctx).cid.count(input as any))),
  } satisfies TRPCRouterRecord);
}
