/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).comorbiditiesValues.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.ComorbiditiesValuesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).comorbiditiesValues.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
