/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.aggregate(input as any)),
      ),

    createMany: procedure
      .input(
        $Schema.DefaultObjectiveInformationInputSchema.createMany.optional(),
      )
      .mutation(async ({ ctx, input }) =>
        checkMutate(
          db(ctx).defaultObjectiveInformation.createMany(input as any),
        ),
      ),

    create: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).defaultObjectiveInformation.create(input as any)),
      ),

    deleteMany: procedure
      .input(
        $Schema.DefaultObjectiveInformationInputSchema.deleteMany.optional(),
      )
      .mutation(async ({ ctx, input }) =>
        checkMutate(
          db(ctx).defaultObjectiveInformation.deleteMany(input as any),
        ),
      ),

    delete: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).defaultObjectiveInformation.delete(input as any)),
      ),

    findFirst: procedure
      .input(
        $Schema.DefaultObjectiveInformationInputSchema.findFirst.optional(),
      )
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input(
        $Schema.DefaultObjectiveInformationInputSchema.findFirst.optional(),
      )
      .query(({ ctx, input }) =>
        checkRead(
          db(ctx).defaultObjectiveInformation.findFirstOrThrow(input as any),
        ),
      ),

    findMany: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(
          db(ctx).defaultObjectiveInformation.findUniqueOrThrow(input as any),
        ),
      ),

    groupBy: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(
          db(ctx).defaultObjectiveInformation.updateMany(input as any),
        ),
      ),

    update: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).defaultObjectiveInformation.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).defaultObjectiveInformation.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.DefaultObjectiveInformationInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).defaultObjectiveInformation.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
