/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.ExamResultsValuesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.ExamResultsValuesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.ExamResultsValuesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.ExamResultsValuesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.ExamResultsValuesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.ExamResultsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.ExamResultsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.ExamResultsValuesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.ExamResultsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.ExamResultsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.ExamResultsValuesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.ExamResultsValuesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.ExamResultsValuesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.ExamResultsValuesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).examResultsValues.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.ExamResultsValuesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).examResultsValues.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
