/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.HealthPlansValuesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.HealthPlansValuesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.HealthPlansValuesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.HealthPlansValuesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.HealthPlansValuesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.HealthPlansValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.HealthPlansValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.HealthPlansValuesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.HealthPlansValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.HealthPlansValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.HealthPlansValuesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.HealthPlansValuesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.HealthPlansValuesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.HealthPlansValuesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).healthPlansValues.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.HealthPlansValuesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).healthPlansValues.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
