/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.InvitationInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.InvitationInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.InvitationInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.InvitationInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.InvitationInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.InvitationInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.InvitationInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.InvitationInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.InvitationInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.InvitationInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.InvitationInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.InvitationInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.InvitationInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.InvitationInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).invitation.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.InvitationInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).invitation.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
