/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.MedicationsValuesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.MedicationsValuesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.MedicationsValuesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.MedicationsValuesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.MedicationsValuesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.MedicationsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.MedicationsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.MedicationsValuesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.MedicationsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.MedicationsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.MedicationsValuesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.MedicationsValuesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.MedicationsValuesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.MedicationsValuesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).medicationsValues.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.MedicationsValuesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).medicationsValues.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
