/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.PatientInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.PatientInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.PatientInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.PatientInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.PatientInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.PatientInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.PatientInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.PatientInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.PatientInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.PatientInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.PatientInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.PatientInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.PatientInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.PatientInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).patient.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.PatientInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).patient.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
