/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.VaccinationsValuesInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.VaccinationsValuesInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.VaccinationsValuesInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.VaccinationsValuesInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.VaccinationsValuesInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.VaccinationsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.VaccinationsValuesInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.VaccinationsValuesInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.VaccinationsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.VaccinationsValuesInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.VaccinationsValuesInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.VaccinationsValuesInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.VaccinationsValuesInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.VaccinationsValuesInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinationsValues.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.VaccinationsValuesInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinationsValues.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
