/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { TRPCRouterRecord } from "@trpc/server";
import * as _Schema from "@zenstackhq/runtime/zod/input";

import { db } from ".";
import { createTRPCRouter, procedure } from "../../trpc";
import { checkMutate, checkRead } from "../helper";

const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;

export default function createRouter() {
  return createTRPCRouter({
    aggregate: procedure
      .input($Schema.VaccinationsInputSchema.aggregate)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.aggregate(input as any)),
      ),

    createMany: procedure
      .input($Schema.VaccinationsInputSchema.createMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.createMany(input as any)),
      ),

    create: procedure
      .input($Schema.VaccinationsInputSchema.create)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.create(input as any)),
      ),

    deleteMany: procedure
      .input($Schema.VaccinationsInputSchema.deleteMany.optional())
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.deleteMany(input as any)),
      ),

    delete: procedure
      .input($Schema.VaccinationsInputSchema.delete)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.delete(input as any)),
      ),

    findFirst: procedure
      .input($Schema.VaccinationsInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.findFirst(input as any)),
      ),

    findFirstOrThrow: procedure
      .input($Schema.VaccinationsInputSchema.findFirst.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.findFirstOrThrow(input as any)),
      ),

    findMany: procedure
      .input($Schema.VaccinationsInputSchema.findMany.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.findMany(input as any)),
      ),

    findUnique: procedure
      .input($Schema.VaccinationsInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.findUnique(input as any)),
      ),

    findUniqueOrThrow: procedure
      .input($Schema.VaccinationsInputSchema.findUnique)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.findUniqueOrThrow(input as any)),
      ),

    groupBy: procedure
      .input($Schema.VaccinationsInputSchema.groupBy)
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.groupBy(input as any)),
      ),

    updateMany: procedure
      .input($Schema.VaccinationsInputSchema.updateMany)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.updateMany(input as any)),
      ),

    update: procedure
      .input($Schema.VaccinationsInputSchema.update)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.update(input as any)),
      ),

    upsert: procedure
      .input($Schema.VaccinationsInputSchema.upsert)
      .mutation(async ({ ctx, input }) =>
        checkMutate(db(ctx).vaccinations.upsert(input as any)),
      ),

    count: procedure
      .input($Schema.VaccinationsInputSchema.count.optional())
      .query(({ ctx, input }) =>
        checkRead(db(ctx).vaccinations.count(input as any)),
      ),
  } satisfies TRPCRouterRecord);
}
